# Generated by Django 5.0.7 on 2024-11-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='course',
            new_name='kurso',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='teacher',
            new_name='professor',
        ),
        migrations.RenameModel(
            old_name='Kurso',
            new_name='Course',
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=255)),
                ('data_moris', models.DateField(null=True)),
                ('sexo', models.CharField(choices=[('Choose Gender', 'Choose Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Choose Gender', max_length=20)),
                ('no_telefone', models.CharField(max_length=15, null=True, unique=True)),
                ('hela_fatin', models.CharField(max_length=255)),
                ('municipio', models.CharField(choices=[('Choose Municipality', 'Choose Municipality'), ('Ainaro', 'Ainaro'), ('Aileu', 'Aileu'), ('Atauro', 'Atauro'), ('Bobonaro', 'Bobonaro'), ('Baucau', 'Baucau'), ('Dili', 'Dili'), ('Cova-Lima', 'Cova-Lima'), ('Ermera', 'Ermera'), ('Liquica', 'Liquica'), ('Lospalos', 'Lospalos'), ('Manatuto', 'Manatuto'), ('Manu-Fahi', 'Manu-Fahi'), ('Viqueque', 'Viqueque')], default='Choose Municipality', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('klase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='estudents.klasse')),
                ('kurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.course')),
                ('materia', models.ManyToManyField(related_name='students', to='estudents.subjects')),
            ],
        ),
        migrations.DeleteModel(
            name='Estudents',
        ),
    ]
