# Generated by Django 5.0.7 on 2024-11-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0002_rename_course_subjects_kurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='municipio',
            field=models.CharField(choices=[('Hili Municipio!', 'Hili Municipio!'), ('Ainaro', 'Ainaro'), ('Aileu', 'Aileu'), ('Atauro', 'Atauro'), ('Bobonaro', 'Bobonaro'), ('Baucau', 'Baucau'), ('Dili', 'Dili'), ('Cova-Lima', 'Cova-Lima'), ('Ermera', 'Ermera'), ('Liquica', 'Liquica'), ('Lospalos', 'Lospalos'), ('Manatuto', 'Manatuto'), ('Manu-Fahi', 'Manu-Fahi'), ('Viqueque', 'Viqueque')], default='Choose Municipality', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='sexo',
            field=models.CharField(choices=[('Hili Sexo!', 'Hili Sexo!'), ('Mane', 'Mane'), ('Feto', 'Feto'), ('Seluk', 'Seluk')], default='Choose Gender', max_length=20),
        ),
    ]
