# Generated by Django 5.0.7 on 2024-11-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0003_alter_students_municipio_alter_students_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='naran_kursos',
            new_name='naran_kurso',
        ),
    ]
