# Generated by Django 5.0.7 on 2024-11-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0004_rename_naran_kursos_course_naran_kurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasse',
            name='kurso',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudents.course'),
        ),
    ]
