# Generated by Django 5.0.7 on 2024-11-05 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0005_klasse_kurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasse',
            name='kurso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudents.course'),
        ),
    ]
