# Generated by Django 5.0.7 on 2024-11-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0006_alter_klasse_kurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='klase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='estudents.klasse'),
        ),
    ]
