# Generated by Django 5.0.7 on 2024-11-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0008_alter_students_klase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klasse',
            name='kurso',
        ),
        migrations.AddField(
            model_name='course',
            name='klase',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='estudents.klasse'),
        ),
    ]
