# Generated by Django 5.0.7 on 2024-11-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0011_alter_course_klase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='kurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudante', to='estudents.course'),
        ),
        migrations.AlterField(
            model_name='students',
            name='materia',
            field=models.ManyToManyField(related_name='materia', to='estudents.subjects'),
        ),
    ]
