# Generated by Django 5.0.7 on 2024-11-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0013_alter_course_klase_alter_students_kurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='materia',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='estudents.subjects'),
        ),
    ]
