# Generated by Django 5.0.7 on 2024-11-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0015_anolectivo_remove_course_klase_controlukursuklase'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlaseEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ativu', 'ativu'), ('nao-ativu', 'nao-ativu')], default='ativu', max_length=20)),
                ('controluestudante', models.ForeignKey(on_delete=models.Model, to='estudents.controlukursuklase')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.students')),
                ('tinan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.anolectivo')),
            ],
        ),
    ]
