# Generated by Django 5.0.7 on 2024-11-08 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0016_klaseestudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klaseestudante',
            name='controluestudante',
            field=models.ForeignKey(on_delete=models.Model, related_name='controlu', to='estudents.controlukursuklase'),
        ),
        migrations.AlterField(
            model_name='klaseestudante',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudante', to='estudents.students'),
        ),
    ]
