# Generated by Django 5.0.7 on 2024-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0017_alter_klaseestudante_controluestudante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='materia',
            field=models.ManyToManyField(default=False, related_name='students', to='estudents.subjects'),
        ),
    ]
