# Generated by Django 5.0.7 on 2024-11-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0017_alter_klaseestudante_controluestudante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='klase',
        ),
        migrations.RemoveField(
            model_name='students',
            name='kurso',
        ),
    ]
