# Generated by Django 5.0.7 on 2024-11-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0017_alter_anolectivo_updated_at_alter_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='klase',
        ),
    ]
