# Generated by Django 5.0.7 on 2024-11-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0018_alter_students_materia'),
        ('estudents', '0018_remove_students_klase_remove_students_kurso'),
    ]

    operations = [
    ]
