# Generated by Django 5.0.7 on 2024-11-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0020_alter_anolectivo_updated_at_alter_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='klase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='estudents.klasse'),
        ),
    ]
