# Generated by Django 5.0.7 on 2024-11-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0019_students_klase_alter_controlukursuklase_kurso'),
        ('estudents', '0022_alter_students_klase_alter_students_kurso'),
    ]

    operations = [
    ]
