# Generated by Django 5.0.7 on 2024-11-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0019_merge_20241110_2320'),
        ('estudents', '0024_alter_controlukursuklase_klase_and_more'),
    ]

    operations = [
    ]
