# Generated by Django 5.0.7 on 2024-11-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0026_students_klase_students_kurso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klaseestudante',
            name='estudante',
        ),
        migrations.AddField(
            model_name='klaseestudante',
            name='estudante',
            field=models.ManyToManyField(to='estudents.students'),
        ),
    ]
