# Generated by Django 5.0.7 on 2024-11-11 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0027_remove_klaseestudante_estudante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='kurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.course'),
        ),
    ]
