# Generated by Django 5.0.7 on 2024-11-11 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0028_alter_students_kurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='klaseestudante',
            name='estudante',
        ),
        migrations.AddField(
            model_name='klaseestudante',
            name='estudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudents.students'),
        ),
    ]
