# Generated by Django 5.0.7 on 2024-11-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0029_remove_students_materia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='klase',
        ),
        migrations.RemoveField(
            model_name='students',
            name='kurso',
        ),
    ]
