# Generated by Django 5.0.7 on 2024-11-11 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0030_remove_students_klase_remove_students_kurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klaseestudante',
            name='tinan',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='klase',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='kurso',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='professor',
        ),
        migrations.CreateModel(
            name='KontroluMateriaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klaseestudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.klaseestudante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.subjects')),
            ],
        ),
    ]
