# Generated by Django 5.0.7 on 2024-11-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0031_remove_klaseestudante_tinan_remove_subjects_klase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrolumateriavalor',
            name='klaseestudante',
        ),
        migrations.AddField(
            model_name='kontrolumateriavalor',
            name='controlukursuklase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estudents.controlukursuklase'),
        ),
    ]
