# Generated by Django 5.0.7 on 2024-11-12 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0032_remove_kontrolumateriavalor_klaseestudante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrolumateriavalor',
            name='controlukursuklase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.controlukursuklase'),
        ),
    ]
