# Generated by Django 5.0.7 on 2024-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0034_rename_kontrolumateriavalor_kontrolumateria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
