# Generated by Django 5.0.7 on 2024-11-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0034_rename_kontrolumateriavalor_kontrolumateria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
