# Generated by Django 5.0.7 on 2024-11-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0035_students_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
