# Generated by Django 5.0.7 on 2024-11-15 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudents', '0036_teacher_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontrolaProfessorMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrolumateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.kontrolumateria')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudents.teacher')),
            ],
        ),
    ]
